name = "JuliOpt"
uuid = "34f9d4c9-18ae-4c05-bb30-62f66462ffc3"
version = "1.0.0-DEV"
authors = ["contributors"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
GraphsFlows = "06909019-6f44-4949-96fc-b9d9aaa02889"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Combinatorics = "1.1.0"
DataStructures = ">=0.18, <0.20"
Graphs = "1.13.4"
GraphsFlows = "0.1.1"
OffsetArrays = "1.17.0"
Revise = "3.13.1"
julia = "1.10.10"

[extras]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Combinatorics", "LinearAlgebra", "Random", "Test"]
