name = "JuliOpt"
uuid = "34f9d4c9-18ae-4c05-bb30-62f66462ffc3"
version = "1.0.0-DEV"
authors = ["contributors"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
DataStructures = "0.19.3"
OffsetArrays = "1.17.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
